name: Development Workflow
on:
  push:
    branches:
      - dev
  workflow_dispatch:
env:
    BACK_IMAGE: temp_server_image
    FRONT_IMAGE: temp_client_image
jobs:
    leakscan:
        runs-on: self-hosted
        steps:
          - name: Get code
            uses: actions/checkout@v4
          
          - uses: gitleaks/gitleaks-action@v2
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              # GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE}}
    trivyfs:
        needs: leakscan
        runs-on: self-hosted
        steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Run Trivy vulnerability scanner in fs mode for frontend
            uses: aquasecurity/trivy-action@0.28.0
            with:
              scan-type: 'fs'
              scan-ref: './client'

          - name: Run Trivy vulnerability scanner in fs mode for backend
            uses: aquasecurity/trivy-action@0.28.0
            with:
              scan-type: 'fs'
              scan-ref: './server'
    sonarqube:
        needs: leakscan
        runs-on: self-hosted
        environment: StorySphere credentials
        continue-on-error: true
        steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Frontend SonarQube Scan
            uses: SonarSource/sonarqube-scan-action@v6.0.0
            env:
                SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
                SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}
            with:
                projectBaseDir: ./client

          - name: Backend SonarQube Scan
            uses: SonarSource/sonarqube-scan-action@v6.0.0
            env:
                SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
                SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}
            with:
                projectBaseDir: ./server
    checkout:
        runs-on: self-hosted
        needs: [trivyfs,sonarqube]
        steps:
            - name: Get code
              uses: actions/checkout@v4

            - name: Verify repo structure
              run: |
                echo "Repository contents:"
                ls -R

            - name: Upload source code
              uses: actions/upload-artifact@v4
              with:
                name: source-code
                path: .
    build:
        needs: checkout
        runs-on: self-hosted
        steps:
            - name: Download source code
              uses: actions/download-artifact@v4
              with:
                name: source-code
                path: .

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Build Backend Image
              run: docker build -t ${{ env.BACK_IMAGE }}:latest -f ./server/Dockerfile ./server

            - name: Build Frontend Image
              run: docker build -t ${{ env.FRONT_IMAGE }}:latest -f ./client/Dockerfile ./client

            - name: Verify built images
              run: docker images
    trivyimage:
        needs: build
        runs-on: self-hosted
        continue-on-error: true
        steps:
            - name: Show Docker images
              run: docker images

            - name: Run Trivy vulnerability scanner for backend image
              uses: aquasecurity/trivy-action@0.28.0
              with:
                image-ref: '${{ env.BACK_IMAGE }}:latest'
                format: 'table'
                exit-code: '0'
                ignore-unfixed: true
                vuln-type: 'os,library'
                severity: 'CRITICAL,HIGH'
                
            - name: Run Trivy vulnerability scanner for frontend image
              uses: aquasecurity/trivy-action@0.28.0
              with:
                image-ref: '${{ env.FRONT_IMAGE }}:latest'
                format: 'table'
                exit-code: '0'
                ignore-unfixed: true
                vuln-type: 'os,library'
                severity: 'CRITICAL,HIGH'
    test:
        needs: build
        runs-on: self-hosted
        steps:
            - name: Show Docker images
              run: docker images

            - name: Create network
              run: |
                    if ! docker network ls | grep -q "tempnet"; then
                      docker network create tempnet
                    fi
        
            - name: Run mysql container
              run: |
                  if docker ps -a | grep "mysql"; then
                    docker rm -f mysql
                  fi
                  docker run -d --name mysql --restart always --network tempnet -e MYSQL_ROOT_PASSWORD=rootpassword -e MYSQL_DATABASE=testDB -e MYSQL_USER=tempuser -e MYSQL_PASSWORD=changepwd -p 3306:3306 mysql:8.0

            - name: Run backend container
              run: |
                  if docker ps -a | grep "backend"; then
                    docker rm -f backend
                  fi
                  docker run -d --name backend --network tempnet -e PORT=80 -e DB_NAME=testDB -e DB_USER=tempuser -e DB_PASS=changepwd -e JWT_SECRET=supersecret -e DB_HOST=mysql -e DB_PORT=3306 -p 80:80 ${{ env.BACK_IMAGE }}

            - name: Run frontend container
              run: |
                  if docker ps -a | grep "frontend"; then
                    docker rm -f frontend
                  fi
                  docker run -d --name frontend -p 3000:3000 ${{ env.FRONT_IMAGE }}

            - name: Test backend health
              run: |
                  echo "Waiting for backend to be ready..."
                  for i in {1..20}; do
                    if docker exec backend curl -fs http://localhost:80/api/health; then
                      echo "✅ Backend is ready!"
                      break
                    fi
                    echo "⏳ Waiting..."
                    sleep 3
                  done
                  if ! docker exec backend curl -fs http://localhost:80/api/health; then
                    echo "❌ Backend health check failed!"
                  fi

            - name: Test frontend accessibility
              run: |
                echo "Waiting for frontend to start..."
                sleep 10
                curl -f http://localhost:3000 || (echo "❌ Frontend not responding!" && exit 1)

            - name: Stop and remove containers
              if: always()
              run: |
                docker ps -a
                docker stop frontend backend mysql || true
                docker rm frontend backend mysql || true
    push:
        needs: test
        runs-on: self-hosted
        environment: StorySphere credentials
        steps:
              - name: Login in docker
                run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

              - name: Tagging the Frontend images
                run: |
                    docker tag ${{ env.FRONT_IMAGE }} ${{ secrets.DOCKERHUB_USERNAME }}/storysphere-frontend-image:latest
                    docker tag ${{ env.FRONT_IMAGE }} ${{ secrets.DOCKERHUB_USERNAME }}/storysphere-frontend-image:${{ github.run_number }}
              - name: Tagging the Backend images
                run: |
                    docker tag ${{ env.BACK_IMAGE }} ${{ secrets.DOCKERHUB_USERNAME }}/storysphere-backend-image:latest
                    docker tag ${{ env.BACK_IMAGE }} ${{ secrets.DOCKERHUB_USERNAME }}/storysphere-backend-image:${{ github.run_number }}

              - name: Pushing the Frontend images
                run: |
                    docker push ${{ secrets.DOCKERHUB_USERNAME }}/storysphere-frontend-image:latest
                    docker push ${{ secrets.DOCKERHUB_USERNAME }}/storysphere-frontend-image:${{ github.run_number }}
              - name: Pushing the Backend images
                run: |
                    docker push ${{ secrets.DOCKERHUB_USERNAME }}/storysphere-backend-image:latest
                    docker push ${{ secrets.DOCKERHUB_USERNAME }}/storysphere-backend-image:${{ github.run_number }}
              
              - name: Verify pushed images
                run: |
                  echo "Checking Docker Hub images..."
                  docker pull ${{ secrets.DOCKERHUB_USERNAME }}/storysphere-backend-image:latest
                  docker pull ${{ secrets.DOCKERHUB_USERNAME }}/storysphere-frontend-image:latest
                  docker images | grep storysphere
              
              - name: Cleaning up images
                if: always()
                run: docker rmi ${{ secrets.DOCKERHUB_USERNAME }}/storysphere-backend-image:latest ${{ secrets.DOCKERHUB_USERNAME }}/storysphere-frontend-image:latest ${{ env.BACK_IMAGE }}:latest ${{ env.FRONT_IMAGE }}:latest ${{ secrets.DOCKERHUB_USERNAME }}/storysphere-backend-image:${{ github.run_number }} ${{ secrets.DOCKERHUB_USERNAME }}/storysphere-frontend-image:${{ github.run_number }}

    #         - name: Checkout repository
    #           uses: actions/checkout@v4

    #         - name: Set up Docker Buildx
    #           uses: docker/setup-buildx-action@v3

    #         - name: Build and push Backend Docker image
    #           uses: docker/build-push-action@v6
    #           with:
    #             context: ./server
    #             file: ./server/Dockerfile
    #             push: true
    #             tags: |
    #               ${{ secrets.DOCKERHUB_USERNAME }}/storysphere-backend-image:latest
    #               ${{ secrets.DOCKERHUB_USERNAME }}/storysphere-backend-image:${{ github.run_number }}

    #         - name: Build and push Frontend Docker image
    #           uses: docker/build-push-action@v6
    #           with:
    #             context: ./client
    #             file: ./client/Dockerfile
    #             push: true
    #             tags: |
    #               ${{ secrets.DOCKERHUB_USERNAME }}/storysphere-frontend-image:latest
    #               ${{ secrets.DOCKERHUB_USERNAME }}/storysphere-frontend-image:${{ github.run_number }}

    # deploy:
    #     needs: push
    #     runs-on: ubuntu-latest
    #     steps:
