name: Production Workflow
on:
  push:
    branches:
      - prod
    paths-ignore:
      - '.github/workflows/**'
  workflow_dispatch:
jobs:
    ci:
      uses: ./.github/workflows/reusable_workflow.yml
      with:
        BACK_IMAGE: "temp_server_image"
        FRONT_IMAGE: "temp_client_image"